import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/Context/useAuth";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <head>
          <link rel="icon" type="image/svg+xml" href="/assets/images/logo-small.png" />
        </head>
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
